language: node_js
node_js:
  - "7"
script:
  - npm run build
  - npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: e2839ada2bc53a023dd979ff9b068e303486333e
  on:
    branch: master