version: '2'
services:
  web:
    build: '.'
    image: web
    ports:
      - 80:8080
    environment:
      EXPRESS_PORT: 8080
      MONGO_URL: 'mongodb://mongo/testing'
  mongo:
    image: mongo
    ports:
      - 27017:27017
